### ISSUE TITLE
distribution: publish on Maven Central

### ISSUE THREAD

**Issue by odeke-em** [opencensus-integrations/ocjdbc#10]
For a distribution channel, we need to publish this work so that it can be included by any one by POM inclusion via Maven Central.

**Comment by odeke-em** [comment]
@songy23 I kindly need your help with publishing to Maven Central. I've prepared everything for this repo, PTAL.

**Comment by songy23** [comment]
To clarify, the artifact name is `io.opencensus:ocjdbc` and the version is `0.0.1`, is that correct?

**Comment by odeke-em** [comment]
Roger that and the package name is: `io.opencensus.ocjdbc`. Thank you @songy23 for taking this on!

**Comment by songy23** [comment]
Release is done. The `io.opencensus:ocjdbc` should be available on Maven in a few minutes.
