### ISSUE TITLE
Update the group id of this artifact.

### ISSUE THREAD

**Issue by songy23** [opencensus-integrations/ocjdbc#16]
Instead of using "io.opencensus", consider "io.opencensus.contrib" or "io.opencensus.integrations".

/cc @bogdandrutu

**Comment by songy23** [comment]
Since we're planning to do a v0.0.2 release soon, I think it's a good time to update the group id now.

**Comment by odeke-em** [comment]
I think `io.opencensus.integrations` would be a match since `io.opencensus.contrib` is where grpc, log-correlation, zpages which are core to the Java OpenCensus project are put.

**Comment by songy23** [comment]
`io.opencensus.integration` sounds good - updated in #17.
