### ISSUE TITLE
all: make wrapper class names different from the interfaces they implement

### ISSUE THREAD

**Issue by bogdandrutu** [opencensus-integrations/ocjdbc#19]
In java is a bad practice to have implementation class have the same name as the interface that they implement because of how imports work in Java.

Consider to change all the class names to something more specific to OpenCensus.
https://github.com/opencensus-integrations/ocjdbc/blob/master/src/main/java/io/opencensus/integration/ocjdbc/CallableStatement.java

Maybe:
WrapCallableStatement
ObservabilityCallableStatement
or any other suggestion is fine.

**Comment by odeke-em** [comment]
@bogdandrutu thanks for the suggestion! I was using these JDBC driver repos as models

Reference|URL
---|---
MySQL Connector/J|https://github.com/mysql/mysql-connector-j/tree/release/5.1/src/com/mysql/jdbc
Microsoft JDBC|https://github.com/MariaDB/mariadb-connector-j/blob/master/src/main/java/org/mariadb/jdbc/

but sure we can make those updates :)

**Comment by bogdandrutu** [comment]
Yes, but your are not actually implementation are wrappers.

**Comment by odeke-em** [comment]
Gotcha, thanks! I've updated the title too here.

**Comment by odeke-em** [comment]
Thanks for the suggestion @bogdandrutu, TIL!
