### ISSUE TITLE
all: use Java variable names and the appropriate final keyword

### ISSUE THREAD

**Issue by bogdandrutu** [opencensus-integrations/ocjdbc#22]
Here:

https://github.com/opencensus-integrations/ocjdbc/blob/master/src/main/java/io/opencensus/integration/ocjdbc/ResultSet.java#L22

This should be
```java
private **final** java.sql.ResultSet **resultSet**;
```

**Comment by odeke-em** [comment]
Roger that, I updated the title to reflect this for easier groking :)
