### ISSUE TITLE
Remove ocjdbc/installJar.sh

### ISSUE THREAD

**Issue by bogdandrutu** [opencensus-integrations/ocjdbc#23]
Use 
```bash
$ ./gradlew install
```

**Comment by odeke-em** [comment]
Cool, I was using `installJar.sh` for local installations because I don't have publishing access but also when running demo apps. Will that comment replace that functionality?

**Comment by songy23** [comment]
> Will that comment replace that functionality?

Yes, `./gradlew installDist` is equivalent.

**Comment by bogdandrutu** [comment]
Sorry no "Dist" just install .

**Comment by bogdandrutu** [comment]
`./gradlew installDist` is when you have an application to build (examples). but just to build and install in the local repo use `./gradlew install`

**Comment by odeke-em** [comment]
@bogdandrutu @songy23 locally running those gives me some exceptions
```shell
$ ./gradlew install
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
Caused by: java.lang.ClassNotFoundException: org.gradle.wrapper.GradleWrapperMain
```

```$ ./gradlew installDist
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
Caused by: java.lang.ClassNotFoundException: org.gradle.wrapper.GradleWrapperMain
```

Btw is this suggestion then to use Gradle instead of Maven?

**Comment by bogdandrutu** [comment]
Can you retry the command now that the jar was added?

**Comment by bogdandrutu** [comment]
@odeke-em correct 👍

**Comment by odeke-em** [comment]
Perfect, thanks!
